### ISSUE TITLE
Segmenting sounds for final stimuli

### ISSUE THREAD

**Issue by danibene** [miso-sound/miso-sound-annotate#11]
@hansen508 following up on our discussion of how to segment the original audio files for the pilot study

[Here](https://github.com/danibene/miso-sound-annotate/blob/9b7d4e51f78ae59c3fe57522e0339b742f8e0ac3/visualization/summary_annotations.md) is a summary of the annotations we have so far. To generate the segmented stimuli files, we still have to decide on various things:

1. Whether to set a minimum/maximum number of sounds per class
2. Whether to set a minimum/maximum duration per sound
3. Whether to limit stimuli to sounds where only one label is present the entire time, or also use multiple labels with [silence](https://github.com/danibene/miso-sound-annotate/blob/9b7d4e51f78ae59c3fe57522e0339b742f8e0ac3/labels/419998_labels.txt) or [other sounds](https://github.com/danibene/miso-sound-annotate/blob/9b7d4e51f78ae59c3fe57522e0339b742f8e0ac3/labels/180150_labels.txt) between them

It's no rush, but I thought it would be good to start thinking more concretely about this, we can always make preliminary decisions and see how they sound

**Comment by danibene** [comment]
@deanorloff I noticed that there's a segmentation file for [125403](https://github.com/miso-sound/miso-sound-annotate/blob/main/segmentation/125403_segment.txt) but not a corresponding label file. Any idea why that is?

**Comment by deanorloff** [comment]
Hi Danielle,

Strange. I'm not sure why that is. After looking, I do not have a label file saved for that sound, suggesting it was not part of the 50 labeled instances. This is puzzling, because I used only the sounds from the google drive folder (it should be there).

I'll check around and see if I can solve this.


[The Ohio State University]


________________________________

**Comment by danibene** [comment]
Hi @deanorloff , sorry to be the bearer of bad news, but it seems like there are multiple instances of segmentation files without corresponding labels files:
|     | term            | url                                                           |   priority | current_term_present   | other_term_present   | notes                         | background_noise_present   |     id |
|----:|:----------------|:--------------------------------------------------------------|-----------:|:-----------------------|:---------------------|:------------------------------|:---------------------------|-------:|
| 260 | clearing throat | https://freesound.org/people/RavenWolfProds/sounds/586979/    |        261 | Yes                    | Yes                  | Others: coughing. Great audio | No                         | 586979 |
| 261 | clearing throat | https://freesound.org/people/dmndrs/sounds/592495/            |        262 | Yes                    | No                   | Female                        | No                         | 592495 |
| 262 | clearing throat | https://freesound.org/people/merrygreen/sounds/336672/        |        263 | Yes                    | No                   | Female                        | No                         | 336672 |
| 263 | clearing throat | https://freesound.org/people/Sukaichae/sounds/546751/         |        264 | Yes                    | No                   | Very punctuated               | No                         | 546751 |
| 264 | clearing throat | https://freesound.org/people/jasonLON/sounds/125403/          |        265 | Yes                    | Yes                  | Others: brief coughing        | No                         | 125403 |
| 267 | swallowing      | https://freesound.org/people/tumiwiththesounds/sounds/501948/ |        268 | Yes                    | No                   | Repeated gulp sound           | No                         | 501948 |
| 268 | swallowing      | https://freesound.org/people/anagar/sounds/267932/            |        269 | Yes                    | No                   | Swallowing water              | No                         | 267932 |
| 271 | swallowing      | https://freesound.org/people/timgormly/sounds/145387/         |        272 | Yes                    | No                   | Swallowing water              | No                         | 145387 |
| 274 | swallowing      | https://freesound.org/people/freakinbehemoth/sounds/243635/   |        275 | Yes                    | No                   | Swallowing water              | No                         | 243635 |

As well as multiple instances of labels files without corresponding segmentation files (which is fine, but we should document our thought process here):

|    | term       | url                                                       |   priority | current_term_present   | other_term_present   | notes                                    | background_noise_present   |     id |
|---:|:-----------|:----------------------------------------------------------|-----------:|:-----------------------|:---------------------|:-----------------------------------------|:---------------------------|-------:|
|  1 | slurping   | https://freesound.org/people/launchsite/sounds/556780/    |          2 | Yes                    | No                   | Straw sound                              | No                         | 556780 |
|  2 | slurping   | https://freesound.org/people/ASMR_Tingles/sounds/530350/  |          3 | Yes                    | Yes                  | Others: swallowing                       | No                         | 530350 |
|  3 | slurping   | https://freesound.org/people/charliemidi/sounds/68145/    |          4 | Yes                    | Yes                  | Others: swallowing, footsteps, murmuring | No                         |  68145 |
|  4 | slurping   | https://freesound.org/people/redcheek/sounds/251984/      |          5 | Yes                    | Yes                  | Others: exhaling, taping mug on table    | No                         | 251984 |
|  5 | slurping   | https://freesound.org/people/bfederi1/sounds/382029/      |          6 | Yes                    | Yes                  | Others: plastic tapping                  | No                         | 382029 |
| 35 | lip smacks | https://freesound.org/people/fthgurdy/sounds/528195/      |         36 | Yes                    | Yes                  | Others: slurping                         | No                         | 528195 |
| 36 | lip smacks | https://freesound.org/people/bmt79/sounds/547234/         |         37 | Yes                    | No                   | Gum chewing                              | No                         | 547234 |
| 37 | lip smacks | https://freesound.org/people/Closetwalrus/sounds/370297/  |         38 | Yes                    | No                   | Gum chewing                              | No                         | 370297 |
| 39 | lip smacks | https://freesound.org/people/yaboiiiiiiiii/sounds/433926/ |         40 | Yes                    | No                   | Quick smacking                           | No                         | 433926 |
| 40 | lip smacks | https://freesound.org/people/justinstroud/sounds/180150/  |         41 | Yes                    | No                   | Eating peanut butter                     | No                         | 180150 |

**Comment by deanorloff** [comment]
Hi Danielle,

Oh wow. I'm not sure why this happened. I don't quite understand how I have segmented files without labels. It seems like I must've made some systematic error here. Sorry for all this.

I'll take a look again at the downloaded 50 sounds that I used for both the labels and the segments. Where are they? The shared drive folder is empty on my end.

I'll also see about making new labels for those sounds that are missing them. Are those all of them?

Thanks,
Dean Orloff


[The Ohio State University]

Dean M. Orloff

Morrill Scholar | Office of Diversity and Inclusion

Neuroscience | College of Arts and Sciences & College of Medicine

Pronouns: he/him/his

________________________________

**Comment by danibene** [comment]
@deanorloff no problem! 

> I'll take a look again at the downloaded 50 sounds that I used for both the labels and the segments. Where are they? The shared drive folder is empty on my end.

I renamed the 50 sounds from the shared drive uploaded them to Zenodo: https://zenodo.org/record/7018063 
Does that format work for you? Let me know if you have any questions.

> I'll also see about making new labels for those sounds that are missing them. Are those all of them?

Yes, the files listed in the first table are all of them. Thank you!
